<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/TraceableValueResolver.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\admin\\ArticleController::add' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::checkUrl' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::delete' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::enable' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::post' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\admin\\TagsController::details' => ['privates', '.service_locator.pom6DQD', 'get_ServiceLocator_Pom6DQDService.php', true],
    'App\\Controller\\admin\\TagsController::lists' => ['privates', '.service_locator.pom6DQD', 'get_ServiceLocator_Pom6DQDService.php', true],
    'App\\Controller\\admin\\TagsController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\admin\\UserController::login' => ['privates', '.service_locator.RnsDnBM', 'get_ServiceLocator_RnsDnBMService.php', true],
    'App\\Controller\\admin\\UserController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\api\\ArticleController::details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\api\\ArticleController::lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\api\\ArticleController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\web\\AdminController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\web\\ArticleController::details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\web\\ArticleController::lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\web\\ArticleController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Lib\\Controller\\AdminBaseController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\admin\\ArticleController:add' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:checkUrl' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:delete' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:enable' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:post' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\admin\\ArticleController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\admin\\TagsController:details' => ['privates', '.service_locator.pom6DQD', 'get_ServiceLocator_Pom6DQDService.php', true],
    'App\\Controller\\admin\\TagsController:lists' => ['privates', '.service_locator.pom6DQD', 'get_ServiceLocator_Pom6DQDService.php', true],
    'App\\Controller\\admin\\TagsController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\admin\\UserController:login' => ['privates', '.service_locator.RnsDnBM', 'get_ServiceLocator_RnsDnBMService.php', true],
    'App\\Controller\\admin\\UserController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\api\\ArticleController:details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\api\\ArticleController:lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\api\\ArticleController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\web\\AdminController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\web\\ArticleController:details' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\web\\ArticleController:lists' => ['privates', '.service_locator.zMBWnHk', 'get_ServiceLocator_ZMBWnHkService.php', true],
    'App\\Controller\\web\\ArticleController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Lib\\Controller\\AdminBaseController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
