<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'App\Service\User' shared autowired service.

include_once $this->targetDirs[3].'/src/Service/User.php';

return $this->privates['App\Service\User'] = new \App\Service\User($this);
