<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'fos_rest.exception.codes_map' shared service.

include_once $this->targetDirs[3].'/vendor/friendsofsymfony/rest-bundle/Util/ExceptionValueMap.php';

return $this->privates['fos_rest.exception.codes_map'] = new \FOS\RestBundle\Util\ExceptionValueMap(['\\Doctrine\\ORM\\EntityNotFoundException' => 404, '\\FOS\\RestBundle\\Exception\\InvalidParameterException' => 404, '\\Exception' => 404, '\\App\\Exception\\LoginException' => 404]);
