<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGrXzbXh\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGrXzbXh/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGrXzbXh.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGrXzbXh\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerGrXzbXh\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'GrXzbXh',
    'container.build_id' => '36e2fc9f',
    'container.build_time' => 1555055264,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGrXzbXh');
