<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXeVCUm8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXeVCUm8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXeVCUm8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXeVCUm8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXeVCUm8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'XeVCUm8',
    'container.build_id' => 'f3d9aa23',
    'container.build_time' => 1554972110,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXeVCUm8');
