<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZAFxdO1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZAFxdO1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZAFxdO1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZAFxdO1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerZAFxdO1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'ZAFxdO1',
    'container.build_id' => '3c6814c4',
    'container.build_time' => 1554688448,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZAFxdO1');
