<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'entry' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~entry.js',
                '/build/entry.js',
            ],
            'css' => [
                '/build/entry.css',
            ],
        ],
    ],
],

]];
